### ISSUE TITLE
Utils.pas

### ISSUE THREAD

**Issue by walwalwalides** [havlicekp/form-designer#1]
Hi,Nice Work 👍 ,it' better to Change the Unit name "Utils.pas" (For Exemple to uUtils.pas) to avoid confusion with native units.
Good continuation

**Comment by havlicekp** [comment]
> 
> 
> Hi,Nice Work 👍 ,it' better to Change the Unit name "Utils.pas" (For Exemple to uUtils.pas) to avoid confusion with native units.
> Good continuation

Hi, Thank you for your recommendation! I'll change the unit name.
